### ISSUE TITLE
회원가입, 로그인, 인증, 인가 개발

### ISSUE THREAD

**Issue by yws1502** [a-daily-diary/ADD.BE#1]
# Todo
- [x] 회원가입 기능
    - [x]  회원가입 API (이메일 형식, 중복 여부 확인, 유저 이름 중복 확인)
    - [x] 이메일 중복 확인 API
    - [x] 유저 이름 중복 확인 API 
- [x] 로그인 기능
- [x] 인증, 인가(authentication, authorization) - jwt 사용

1차 목표
- 회원가입, 로그인, 인증, 인가 기능까지 구현

2차 목표
- 간편 로그인 기능 구현(소셜 로그인)
