### ISSUE TITLE
댓글 sub issue - 협업 문서 최신화(swagger, API 설계 문서)

### ISSUE THREAD

**Issue by yws1502** [a-daily-diary/ADD.BE#41]
## 상위 이슈

- #40

## TODO
- [ ] 각 API swagger 적용
- [ ] notion API 설계 문서 최신화
- [ ] table field 변경 시 ERD 수정

**Comment by yws1502** [comment]
#43 #44 #45 각 이슈에 swagger 적용 부분을 넣어 해당 이슈는 닫겠습니다.
